### ISSUE TITLE
How to download genome sequences(and gtf/gff) file?

### ISSUE THREAD

**Issue by xiekunwhy** [BioOmics/iSeq#1]
Hi,

How to download genome sequences(and gtf/gff) file using iseq, for example, if I want to download GCF_023101765.2, iseq -i GCF_023101765.2 not works.

Best,
Kun

**Comment by BioOmics** [comment]
Hi, @xiekunwhy 

Thank you for using iSeq. I'm sorry, iSeq is currently mainly used to obtain high-throughput sequencing raw data from databases such as GSA, SRA, ENA, etc., rather than for obtaining genomic sequence data.

To help you fetch the data, you can click on this link to [view](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_023101765.2/) genomic information on NCBI GENOME database, or click here to [download](https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/accession/GCF_023101765.2/download?include_annotation_type=GENOME_FASTA&include_annotation_type=GENOME_GFF&include_annotation_type=RNA_FASTA&include_annotation_type=CDS_FASTA&include_annotation_type=PROT_FASTA&include_annotation_type=SEQUENCE_REPORT&hydrated=FULLY_HYDRATED) directly.

Best
