### ISSUE TITLE
Cannot recognize file input

### ISSUE THREAD

**Issue by dysci2022** [BioOmics/iSeq#10]
When I use tab separated files as input, the program cannot recognize them

```
(iseq) server@server:/media/server/work/dy/iseq$ cat list.txt
DRR097288
DRR097303
DRR097304
(iseq) server@server:/media/server/work/dy/iseq$ iseq -i list.txt
 is not a valid Study, Sample, Experiment, or Run accession.
```
When using a separate name as input, it can run normally

```
(iseq) server@server:/media/server/work/dy/iseq$ iseq -i DRR097288
      DRR097288	7.72G
Note: Above Run will be downloaded. You can see the details in DRR097288.metadata.tsv
```
iseq Version 1.2.0 
Thanks a lot!

**Comment by BioOmics** [comment]
Hi,

I am running normally.  
![image](https://github.com/user-attachments/assets/e630613c-c21e-42f3-9940-0ff5a5bc0d23)

Please check the text encoding format of your `list.txt` file. It's most likely an issue because the file was generated in Windows and then transferred to Linux. You can use `vim` to recreate the `list.txt` file, or change the encoding format to Unix (LF) and UTF-8 instead of Windows (CR LF).

If you have any further questions, feel free to ask.

**Comment by dysci2022** [comment]
Thank you for your reply!
That's indeed the reason. After I changed the txt file to Unix (LF), it can now run normally.
Best wishes.
