### ISSUE TITLE
High Failure Rate When Downloading Data

### ISSUE THREAD

**Issue by zhanxiangzong** [BioOmics/iSeq#15]
Hi!
First and foremost, I want to express my gratitude for providing such a useful tool.
I’ve been using iseq recently, and I’ve noticed a significantly higher failure rate when downloading data from ENA using the command iseq -i PRJNA273563 -p 4 -d ena -g. This failure rate seems to be much higher compared to using wget or ascp directly. Similarly, the failure rate when downloading data from SRA is also higher than when using the SRA Toolkit directly.
I’m not sure if this is just a perception on my part (perhaps due to network fluctuations during the download process), or if there’s something inherent in iseq’s mechanisms that could be causing this. Is there any way to adjust or optimize the settings to improve the success rate?
Thank you once again for your time and effort. I look forward to your response.
Best regards

**Comment by BioOmics** [comment]
First, the `-p` option invokes Axel for multi-threaded downloads. Multi-threaded downloads, due to data splitting and merging, are more prone to failures, which could be the primary cause of the issue. You may try using the `-a` option instead. Additionally, iSeq offers robust resume functionality. You can interrupt and restart downloads at any time, and iSeq will check the current folder for incomplete or failed downloads the next time you start. Therefore, simply re-executing the same code can help avoid a high failure rate.  

Moreover, **PRJNA273563** involves 1,135 samples, and prolonged downloads could also lead to errors.  

You mentioned that "the failure rate when downloading data from SRA is also higher than when using the SRA Toolkit directly." Do you have statistical data to support this? Additionally, since the download logic between the two methods may differ, iSeq first retrieves the download link for each SRR via `srapath` and then uses `wget`, `aspera`, or `axel` for downloading, while `prefetch` directly accesses and downloads via HTTPS.  

Moving forward, I plan to optimize the code to address the **High Failure Rate** issue, so stay tuned!

**Comment by zhanxiangzong** [comment]
Thanks for your reply, I will try the -a parameter download.
I don't have very precise statistics, but a rough overview, using PRJNA273563 as an example, when downloading data (.fq.gz) from ebi, I had over two hundred files fail in a single iseq download run, and it took two to three resume runs to get all the data down. When downloading data from SRA or GSA (e.g., downloading CRA005979), splitting the data into multiple copies and downloading with prefetch or wget followed by vdb-validate or md5 validation, there were no problems with any of the files, but with iseq multithreaded downloads, the fail.log file occasionally had single-digit numbers of failed files ( CRA005979 had four failed file downloads), requiring a rerun.
I'm very much looking forward to the optimized version, thanks.
